.\" Copyright (C) 2020-2023, 2025 |Méso|Star> (contact@meso-star.com)
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program. If not, see <http://www.gnu.org/licenses/>.
.Dd March 1, 2025
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.Dt SMSH2VTK 1
.Os
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.Sh NAME
.Nm smsh2vtk
.Nd convert
.Xr smsh 5
mesh to VTK format
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.Sh SYNOPSIS
.Nm
.Op Fl o Ar output
.Ar mesh
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.Sh DESCRIPTION
.Nm
converts a triangular or tetrahedral mesh saved in
.Xr smsh 5
format to legacy VTK format.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl o Ar output
Output file.
If not defined, output data is written to standard output.
.El
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.Sh EXIT STATUS
.Ex -std
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.Sh EXAMPLES
Convert the
.Xr smsh 5
.Pa input.smsh
mesh to VTK format and saves the results in the
.Pa output.vtk
file:
.Bd -literal -offset Ds
smsh2vtk -o output.vtk input.smsh
.Ed
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.Sh SEE ALSO
.Xr smsh 5
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.Sh STANDARDS
.Rs
.%B The VTK User's Guide
.%O Simple Legacy Formats
.%I Kitware, Inc
.%N 11
.%D 2010
.%P 470--482
.Re
